
---
    parser: "@typescript-eslint/parser"
    extends:
      # Uses the recommended rules from the @typescript-eslint/eslint-plugin
      - plugin:@typescript-eslint/recommended
      # Uses eslint-config-prettier to disable ESLint rules from @typescript-eslint/eslint-plugin that would conflict with prettier
      - prettier
      # Enables eslint-plugin-prettier and displays prettier errors as ESLint errors.
      - plugin:prettier/recommended
      # Enables eslint-plugin-openapi and displays Jsdoc notation errors as ESLint errors.
      - plugin:openapi/recommended
    parserOptions:
      ecmaVersion: 2019
      sourceType: module
    rules:
      "@typescript-eslint/prefer-optional-chain": error
      object-shorthand: error
      prefer-destructuring: error
    overrides:
      -
        files:
          - "**/*.{spec,test}.{ts,tsx}"
        rules:
          "@typescript-eslint/ban-ts-ignore": "off"
          "@typescript-eslint/camelcase": "off"
          "@typescript-eslint/no-explicit-any": "off"
          "@typescript-eslint/no-non-null-assertion": "off"
      -
        files:
          - "**/*.tsx"
        rules:
          "@typescript-eslint/explicit-function-return-type": "off"